config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'dashboards#index'

  resources :properties
  resources :wildlifes

end

app/models/animal.rb
class Animal < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/plot.rb
class Plot < ActiveRecord::Base
end

app/models/property.rb
class Property < ActiveRecord::Base

# Stocking - a quantitative measure of the area occupied by trees relative to an optimum or desired level of density
# Stand Density Index - a measure of the stocking of a stand of trees based on the number of trees per unit area and DBH of the tree of average basal area
# Volume table - a chart based on volume equations that uses correlations between certain aspects of a tree to estimate the standing volume
# Stand density management diagram - model that uses current stand density to project future stand composition

end

app/models/soil.rb
class Soil < ActiveRecord::Base
end

app/models/tree.rb
class Tree < ActiveRecord::Base
end

app/models/tree_diameter.rb
class TreeDiameter < ActiveRecord::Base
  has_one :tree

  belongs_to :inventory
end

app/models/tree_inventory.rb
class TreeInventory < ActiveRecord::Base
  belongs_to :property

  has_many :tree_diameters

  def mean_tree_diameters
    tree_map = Hash.new { [] }

    self.tree_diameters.each do |td|
      tree_map[td.tree] << td.diameter
    end

    tree_means = Hash.new { 0 }
    tree_map.each do |k, v|
      tree_means[k] = v.reduce(:+) / tree_means[k].length rescue 0
    end

    # Take an average by tree.

    tree_means
  end

   # From the data collected one can calculate the number of trees per acre, the basal area, the volume of trees in an area, and the value of the timber.
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :inventories
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wildlife.rb
class Wildlife < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # TODO: Show the polygons which are the properties.
  # TODO: Create a new property with the correct boundaries
  # TODO: List the properties

  def index
    @properties = Property.all
  end

  def show

  end
end

app/controllers/wildlifes_controller.rb
class WildlifesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/wildlifes_helper.rb
module WildlifesHelper
end

app/views/dashboards/index.html.erb
<h1 class="page-header">Dashboard</h1>

<div class="row placeholders">
  <div class="col-xs-6 col-sm-3 placeholder">
    <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
</div>

<h2 class="sub-header">Section title</h2>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
        <th>Header</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1,001</td>
        <td>Lorem</td>
        <td>ipsum</td>
        <td>dolor</td>
        <td>sit</td>
      </tr>
      <tr>
        <td>1,002</td>
        <td>amet</td>
        <td>consectetur</td>
        <td>adipiscing</td>
        <td>elit</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>Integer</td>
        <td>nec</td>
        <td>odio</td>
        <td>Praesent</td>
      </tr>
      <tr>
        <td>1,003</td>
        <td>libero</td>
        <td>Sed</td>
        <td>cursus</td>
        <td>ante</td>
      </tr>
      <tr>
        <td>1,004</td>
        <td>dapibus</td>
        <td>diam</td>
        <td>Sed</td>
        <td>nisi</td>
      </tr>
      <tr>
        <td>1,005</td>
        <td>Nulla</td>
        <td>quis</td>
        <td>sem</td>
        <td>at</td>
      </tr>
      <tr>
        <td>1,006</td>
        <td>nibh</td>
        <td>elementum</td>
        <td>imperdiet</td>
        <td>Duis</td>
      </tr>
      <tr>
        <td>1,007</td>
        <td>sagittis</td>
        <td>ipsum</td>
        <td>Praesent</td>
        <td>mauris</td>
      </tr>
      <tr>
        <td>1,008</td>
        <td>Fusce</td>
        <td>nec</td>
        <td>tellus</td>
        <td>sed</td>
      </tr>
      <tr>
        <td>1,009</td>
        <td>augue</td>
        <td>semper</td>
        <td>porta</td>
        <td>Mauris</td>
      </tr>
      <tr>
        <td>1,010</td>
        <td>massa</td>
        <td>Vestibulum</td>
        <td>lacinia</td>
        <td>arcu</td>
      </tr>
      <tr>
        <td>1,011</td>
        <td>eget</td>
        <td>nulla</td>
        <td>Class</td>
        <td>aptent</td>
      </tr>
      <tr>
        <td>1,012</td>
        <td>taciti</td>
        <td>sociosqu</td>
        <td>ad</td>
        <td>litora</td>
      </tr>
      <tr>
        <td>1,013</td>
        <td>torquent</td>
        <td>per</td>
        <td>conubia</td>
        <td>nostra</td>
      </tr>
      <tr>
        <td>1,014</td>
        <td>per</td>
        <td>inceptos</td>
        <td>himenaeos</td>
        <td>Curabitur</td>
      </tr>
      <tr>
        <td>1,015</td>
        <td>sodales</td>
        <td>ligula</td>
        <td>in</td>
        <td>libero</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Forestly</title>

    <!-- Bootstrap core CSS -->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

    <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCuumbhIfdAXEp93h5SJ7HlLd1kKdqYSQM"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= yield :head %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Forestly</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Dashboard", root_path %></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><%= link_to "Overview", root_path %></a></li>
            <li><%= link_to "Properties", properties_path %></li>
            <!--
            <li><a href="#">Export</a></li>
            -->
          </ul>
          <ul class="nav nav-sidebar">
            <li><%= link_to "Wildlife", wildlifes_path %></li>
            <li><a href="">Plants</a></li>
          </ul>

          <!--
          <ul class="nav nav-sidebar">
            <li><a href="">Nav item again</a></li>
            <li><a href="">One more nav</a></li>
            <li><a href="">Another nav item</a></li>
          </ul>
          -->
        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/properties/index.html.erb
<% content_for :head do %>
  <style>
  </style>

  <script type="text/javascript">
   var map;

   function initialize() {
     var mapOptions = {
       zoom: 8,
       center: new google.maps.LatLng(-25.363882, 131.044922)
     };

     map = new google.maps.Map(document.getElementById('wildlife-map-canvas'), mapOptions);

     var marker = new google.maps.Marker({
       position: map.getCenter(),
       map: map,
       title: 'Click to zoom'
     });

     google.maps.event.addListener(map, 'center_changed', function() {
       // 3 seconds after the center of the map has changed, pan back to the
       // marker.
       window.setTimeout(function() {
         map.panTo(marker.getPosition());
       }, 3000);
     });

     google.maps.event.addListener(marker, 'click', function() {
       map.setZoom(8);
       map.setCenter(marker.getPosition());
     });
   }

   $(function() {
     google.maps.event.addDomListener(window, 'load', initialize);
   });
  </script>
<% end %>

<h1 class="page-header">Properties</h1>

<div class="row placeholders">
  <div id="wildlife-map-canvas"></div>
</div>

<div class="row">

</div>

<div class="row">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Estimated Value</th>
    </thead>
    <% @properties.each do |prop| %>
      <tr>
        <td><%= link_to prop.name, property_path(prop) %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/properties/show.html.haml
%div
  Interpolation

%div
  Sample

%div
  %h2 New Inventory
  %ul
    %li Model-Based Inference
    %li Random Sampling

app/views/wildlifes/index.html.erb
<% content_for :head do %>
  <style>
  </style>

  <script type="text/javascript">
   var map;

   function initialize() {
     var mapOptions = {
       zoom: 8,
       center: new google.maps.LatLng(-25.363882, 131.044922)
     };

     map = new google.maps.Map(document.getElementById('wildlife-map-canvas'), mapOptions);

     var marker = new google.maps.Marker({
       position: map.getCenter(),
       map: map,
       title: 'Click to zoom'
     });

     google.maps.event.addListener(map, 'center_changed', function() {
       // 3 seconds after the center of the map has changed, pan back to the
       // marker.
       window.setTimeout(function() {
         map.panTo(marker.getPosition());
       }, 3000);
     });

     google.maps.event.addListener(marker, 'click', function() {
       map.setZoom(8);
       map.setCenter(marker.getPosition());
     });
   }

   $(function() {
     google.maps.event.addDomListener(window, 'load', initialize);
   });
  </script>
<% end %>

<h1 class="page-header">Wildlife</h1>

<div class="row placeholders">
  <div id="wildlife-map-canvas"></div>
</div>